# Generated by Django 3.2.8 on 2021-10-31 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_pk', models.CharField(default='0', max_length=200)),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(default='Guest', max_length=200)),
                ('site_id', models.IntegerField()),
                ('webhook_id', models.CharField(default='0', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dscription', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='back.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='back.task')),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='back.userinfo')),
            ],
        ),
    ]
