# Generated by Django 3.2.8 on 2021-11-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_estimate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='TimeTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=300)),
                ('before', models.IntegerField()),
                ('after', models.IntegerField()),
                ('date', models.CharField(max_length=300)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='back.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='back.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Assignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assingees', to='back.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='back.userinfo')),
            ],
        ),
    ]
