# Generated by Django 3.2.8 on 2021-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
