# Generated by Django 3.2.8 on 2021-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20211110_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetaskhistory',
            name='time_id',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='timetaskhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
