# Generated by Django 3.2.8 on 2021-10-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='api_pk',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='webhook_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
