# Generated by Django 3.2.8 on 2021-10-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20211031_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='back.userinfo'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='back.userinfo'),
        ),
    ]
